runtime: nodejs
env: flex
beta_settings:
  cloud_sql_instances: word-builder-app.mysql.database.azure.com
env_variables:
  DB_USER: test-user
  DB_PASS: "Qwertyuiop["
  DB_NAME: sentence-builder-app-db

  #DB_SOCKET: /word-builder-app.mysql.database.azure.com
